version: "3.9"
services:
  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db_accounts'
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
  nagp-devops-assignment:
    image: "naveenbhardwaj/nagp-devops-assignment"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - 9001:9001